RABSW-432: dws-operator: Clean up REST test scripts

diff --git a/test/rest/getcrd b/test/rest/getcrd
--- a/test/rest/getcrd
+++ b/test/rest/getcrd
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 [[ "$1" = "all" ]] || rname=$1
 
 DWSHOST=${DWSHOST:-localhost}
@@ -10,7 +12,7 @@ error_exit()
 }
 
 echo Get $rname ...
-raw=`curl  -X GET "http://${DWSHOST}:${DWSPORT}/apis/apiextensions.k8s.io/v1/customresourcedefinitions/${rname}" -H "Content-Type: application/json"` || echo "get failed"
+raw=$(curl  -X GET "http://${DWSHOST}:${DWSPORT}/apis/apiextensions.k8s.io/v1/customresourcedefinitions/${rname}" -H "Content-Type: application/json") || echo "get failed"
 
 errcode=`echo $raw | jq '.code'`
 errreason=`echo $raw | jq '.reason'`
@@ -18,13 +20,12 @@ errreason=`echo $raw | jq '.reason'`
 #[[ "$errcode" = "null" ]] || error_exit $errcode $errreason
 
 if [ "$1" = "all" -o "$2" = "all" ]; then
-    #echo $raw | jq '.'
-    echo $raw 
+    echo $raw | jq '.'
 else
 
     if [ -z "$2" -o  "$2" = "meta" ]; then
         echo Metadata:
-        echo $raw | jq '[.metadata.name, .metadata.namespace, .metadata.resourceVersion]'
+        echo $raw | jq '.metadata'
     fi
 
     if [ -z "$2" -o  "$2" = "spec" ]; then
